### ISSUE TITLE
abnormal operation with ky-040 encoder button

### ISSUE THREAD

**Issue by jandes62** [phts/NP-01_buttons#1]
Hi,
I installed your plugin on volumio 3 system because I need to implement long press action on some buttons. I noticed that on a normal button the shutdown function works well, while the play function on encoder button does not work well, it is necessary to double push. What could this be due to?
I'm not a programmer but I tried changing the value of debounce timeout in index.js but nothing.

I apologize for mi bad english
thanks

**Comment by phts** [comment]
This app supposed to be used with my device with normal buttons. No idea about encoder buttons to be honest.

This app uses [onoff](https://www.npmjs.com/package/onoff) package. Try to find info about rotary buttons there, maybe they require specific logic to handle them.

But as I know encoder buttons have completely different nature, are they even fit into this library usage? 🤔 Probably there should be other package to handle encoder buttons
